### ISSUE TITLE
Firewall rule issue

### ISSUE THREAD

**Issue by dperson** [robbertkl/docker-ipv6nat#11]
First, big thanks for creating this project, it's crazy that it's not built into docker by default.

I'm running Fedora 25, fully patched and up to date. After starting your container, the forwarding rules worked on the local host, but not remotely (even on the same local network). On checking the firewall forwarding chain, I found the issue. Your docker rules were added after the default deny, so were never actually reached:
```
dperson@tundro$ sudo ip6tables -S FORWARD                                                           
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -j FORWARD_direct
-A FORWARD -j FORWARD_IN_ZONES_SOURCE
-A FORWARD -j FORWARD_IN_ZONES
-A FORWARD -j FORWARD_OUT_ZONES_SOURCE
-A FORWARD -j FORWARD_OUT_ZONES
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -j REJECT --reject-with icmp6-adm-prohibited
-A FORWARD -o docker1 -j DOCKER
-A FORWARD -o docker1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker1 ! -o docker1 -j ACCEPT
-A FORWARD -i docker1 -o docker1 -j ACCEPT
```

I ran the following 2 commands:
```
dperson@tundro$ sudo ip6tables -D FORWARD -j REJECT --reject-with icmp6-adm-prohibited              
dperson@tundro$ sudo ip6tables -A FORWARD -j REJECT --reject-with icmp6-adm-prohibited
```

Then things worked with the following FORWARD chain:
```
dperson@tundro$ sudo ip6tables -S FORWARD                                                           
-P FORWARD ACCEPT
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -j FORWARD_direct
-A FORWARD -j FORWARD_IN_ZONES_SOURCE
-A FORWARD -j FORWARD_IN_ZONES
-A FORWARD -j FORWARD_OUT_ZONES_SOURCE
-A FORWARD -j FORWARD_OUT_ZONES
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -o docker1 -j DOCKER
-A FORWARD -o docker1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker1 ! -o docker1 -j ACCEPT
-A FORWARD -i docker1 -o docker1 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp6-adm-prohibited
```

If there are `REJECT` or `DROP` rules in the chain before the rules you add, can you have your container automatically `-D` (delete) and `-A` (append them), or insert your rules before them in the first place? Thanks.

**Comment by rmoriz** [comment]
This issue is also present with debian when using `ufw`

**Comment by JiiPee74** [comment]
I have this same issue and what I think ipv6nat should do is to detect if there already rules set, it should add docker related rules with -I not with -A and then not add any REJECT/DROP rules if they are already present.

**Comment by robbertkl** [comment]
I'd like to mimic the way docker handles this situation for IPv4. I hope to take a crack at this soon, but I'm a bit busy at the moment. In the meantime PRs (or additional info on how docker does this) are very welcome.

**Comment by JiiPee74** [comment]
Example here is commit so docker recreate rules when firewalld reload is issued

https://github.com/docker/libnetwork/commit/dbc253f732f8f1d90306e4128fb05bdc59f61544

**Comment by JiiPee74** [comment]
And I think here is some detection if firewalld is running, not sure if it explain how rules are added
https://github.com/docker/libnetwork/blob/v0.8.0-dev.2/iptables/iptables.go#L351

And here is when firewalld support was added to docker
https://github.com/moby/moby/pull/9397

**Comment by robbertkl** [comment]
The last one (firewalld) seems like quite a big change: when firewalld is detected it uses firewalld instead of iptables directly. Would this be necessary, or do you think we can just talk to iptables and co-exist with firewalld (just having to manage where to place rules and watch out for restarts / firewall clears)?

**Comment by JiiPee74** [comment]
I don't think it's required to use firewalld to add rules, it will after all use iptables to add thouse rules. So if there is way to detect firewalld restart/reload event, then yes I think it would be enough to just fill rules again.

So if docker use firewalld to add rules if it detects it's active, I ques there isn't any trace to see where in chain it's adding thouse rules?

Anyway my experience is that docker related rules are added top of the chain.

**Comment by dperson** [comment]
Whether they are managed by `firewalld` or directly in `iptables` should make no difference.

The key is getting them inserted before the final `DROP` or `REJECT` rule. There are often good rules to protect from bogus/malicious traffic. If it's not too much work, I'd prefer that the docker rules be `-I` (inserted) before the last rule (if it's `DROP` or `REJECT`). Thanks.

**Comment by imp1sh** [comment]
I also have the exact same Problem with CentOS 7.

**Comment by imp1sh** [comment]
This issue is also valid for Fedora 26.

**Comment by Strayer** [comment]
Did anyone find a way to get this easily usable with UFW? I'd really like to start using this and add IPv6 functionality to my containers, but it seems like UFW is making this kinda impossible :/

**Comment by robbertkl** [comment]
Finally had some time to look into this, sorry for the delay!

I've made some changes to make it play nice with existing firewall rules. I've tested it on a Debian Stretch VM with UFW, but it should work with other firewall conflicts as well.

I've released a new version ([v0.3.1](https://github.com/robbertkl/docker-ipv6nat/releases/tag/v0.3.1)) which is also available from Docker Hub as `robbertkl/ipv6nat:latest` or `robbertkl/ipv6nat:v0.3.1`.

Could you all try this out and let me know here if it works for you? Thanks!

**Comment by dperson** [comment]
Yes, that fixes it for me. Thank you very much.

**Comment by Strayer** [comment]
Seems to work fine for me on Gentoo with docker 17.03.2-ce! Initially had a different issue... didn't set a default IPv6 gateway, starting Docker with ipv6 broke the whole IPv6 network - ouch! After that was sorted I started the ipv6nat container again and the forwarding seems to set up just fine.

In future I'll probably move to [manual firewall configuration with nftables](https://stephank.nl/p/2017-06-05-ipv6-on-production-docker.html) - much easier to handle than iptables and there aren't too many publically exposed containers on my server anyway. Also don't really like that Docker "bypasses" my firewall rules.

Thanks for fixing this!

**Comment by robbertkl** [comment]
Thanks @dperson and @Strayer for letting me know. Glad to hear it's working now.
