### ISSUE TITLE
iptables v1.6.1: Couldn't load target `DOCKER'

### ISSUE THREAD

**Issue by setiseta** [robbertkl/docker-ipv6nat#13]
Hello,

i have tried to get this working, but the ipv6nat container is in restarting state with the log message:
2017/06/19 07:21:03 exit status 2: iptables v1.6.1: Couldn't load target `DOCKER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

help would be nice.
What am i doing wrong?

Kind Regards
Sebastian

**Comment by setiseta** [comment]
this appears if option b is used on ubuntu 16.04.
If i run option A on this system i get a message about the modules missing, and with mounting the additional volume it works.
so this may be a minor thing?
is the module loading missing / not working on option B?

**Comment by robbertkl** [comment]
Can you send me some additional info:
* Docker version
* Docker daemon startup flags
* Command (or compose section) you used to start the container
* Output of `docker run --rm --privileged --net=host --entrypoint iptables-save robbertkl/ipv6nat`

**Comment by setiseta** [comment]
The Host with only option B:
- Docker Version: 17.05.0-ce
- Docker daemon startup flags:
   ```DOCKER_OPTS="--log-opt max-size=100m --log-opt max-file=5 --userland-proxy=false"```
- Command:
   ```docker run --name ipv6nat -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock:ro --privileged --net=ipv6test -v /lib/modules:/lib/modules:ro robbertkl/ipv6nat```
- Output of iptables-save
  - is very huge, as this host runs alot of containers, and i wanted to test ipv6 nat as of the default ipv6 implementation is not usable 4 me. should i search something special in the output?
  - this is the reasion why testing with option B from readme

**Comment by robbertkl** [comment]
You're missing `--net=host`.

**Comment by robbertkl** [comment]
I see now you have `--net=ipv6test`; this is incorrect. The ipv6nat container needs to have access to the host firewall. See `README.md`.

**Comment by robbertkl** [comment]
Just clarified this in the README in 4395f915199c447f385b19710d5ced4c786dc5a9.

**Comment by setiseta** [comment]
Thank you for fast response.
