### ISSUE TITLE
Ports bond to localhost are not ignored

### ISSUE THREAD

**Issue by mettke** [robbertkl/docker-ipv6nat#15]
Adding a Container with 
```
docker run -p ":::5000:5000" -it alpine /bin/ash
```
leads to the following ip6table rules:
```
Chain DOCKER (5 references)
target     prot opt source               destination         
ACCEPT     tcp      ::/0                 fd00:1::2            tcp dpt:5000
```
However being bond to localhost, the port should not be exposed like that.

**Comment by robbertkl** [comment]
First of all, `::` is not localhost. Localhost is `::1`. `::` is the equivalent of `0.0.0.0/0`, i.e. "anywhere".

Secondly, Docker / `docker run` does not support IPv6 port binding. `ipv6nat` is an external service that does not modify the behavior of docker. `-p` is for docker's own IPv4 bindings.

**Comment by robbertkl** [comment]
You could, however, try using `com.docker.network.bridge.host_binding_ipv6` on a user-defined network, like is explained in the README.

**Comment by mettke** [comment]
Docker does support Ipv6 Ports.
My command was wrong the correct one is:
```
docker run -p "[::1]:6000:6000" -it alpine /bin/ash
```
Also using docker-compose.yml ports can be defined using:
```
    ports:
      - ":::5000:5000"
```
More info at https://github.com/docker/compose/issues/5020

**Comment by mettke** [comment]
And iptables from docker does not add a port forwarding as well

**Comment by robbertkl** [comment]
My guess is binding to `::1` would have the userland proxy forward it. It won't add an IPv4 forwarding rule, because it's not bound to an IPv4 address and it won't add an IPv6 forwarding rule because Docker does not do IPv6 NAT.

**Comment by robbertkl** [comment]
Just to be clear, are you still having an issue now you have the correct command? If so, I'll reopen.

**Comment by mettke** [comment]
I just posted the incorrect command. The issue is still there.
I might be mistaken but as far as I understand it 
```
[::1]:8080:8080
127.0.0.1:8080:8080
```
are made for the same purpose. To expose a port only to the host and not to the outside.
127.0.0.1 however only works for ipv4 and [::1] for both

docker-compose added that functionality as well only that they use 
```
:::8080:8080
```
(for whatever reason instead of ::1) as replacement for "127.0.0.1:8080:8080"

You are right that normally "::" anywhere - however this is not given for docker-compose as they decided to use it for ipv6 and ipv4 localhost

**Comment by mettke** [comment]
Ok now I see my problem. docker compose can use ::1:8080:8080 as well. 
With that there are still unnecessary rules created but they are not a problem 'cause they are bond to localhost

```
-A DOCKER -d ::1/128 -p tcp -m tcp --dport 5000 -j DNAT --to-destination [fd00:1::2]:5000
```

Sorry for the heat. Works pretty nice now :+1:

**Comment by robbertkl** [comment]
No problemo. Thanks for reporting! ipv6nat doesn't really treat localhost any differently, which is why you'd see that rule I guess.

Also, still not really sure what a published port with an IPv6 address binding would do in regular Docker without ipv6nat, aside from maybe altering the userland proxy behavior. I was under the impression that Docker's IPv6 support is meant for giving containers globally routable IPv6 addresses, and therefore making publishing ports kind of useless.
