### ISSUE TITLE
Container has always latest added ipvt

### ISSUE THREAD

**Issue by blockmover** [robbertkl/docker-ipv6nat#18]
Thanks Robbert for the tool it's really really great and it help me a lot.
I run several containers and each gets a unique network and should connect to the outside world with it a dedicated ipv6 from the host. When I run your container all my other container use the latest ipv6 from the host.
To fix that I had to run 
sudo ip6tables -t nat -I POSTROUTING -s fd00:dead:ab::/48 -j SNAT --to-source [ipv6 address] then it worked.
Maybe you can have a look at it.

***
here the command I used to create the network
docker network create --ipv6 --subnet fd00:dead:ab::/48 --gateway fd00:dead:ab::1 -o "com.docker.network.bridge.host_binding_ipv6"="[ipv6 address" bridge_container1_ipv6

**Comment by robbertkl** [comment]
Hi @blockmover, thanks for reporting!

I don't have that issue myself, it works without the SNAT rule here. Let's figure out what's different from your setup and why it's needed.

What about IPv4. Does your docker also add a similar rule to your IPv4 iptables? (check output of `iptables-save`)

If you know how and when this rule is needed, a PR for this project would also be very welcome!

**Comment by robbertkl** [comment]
Closed due to inactivity. Just reopen if needed.
