### ISSUE TITLE
IPv6 stop working on host

### ISSUE THREAD

**Issue by navossoc** [robbertkl/docker-ipv6nat#20]
**Information:**
- Debian 9.4 x64
- Docker version 18.03.0-ce, build 0520e24
- docker-compose version 1.20.1, build 5d8c71b
- docker-ipv6nat.amd64: v0.3.2
- robbertkl/ipv6nat:latest

**How to test:**

Configure ipv6 on the default bridge network adapter:
`/etc/docker/daemon.json`

```json
{
  "ipv6": true,
  "fixed-cidr-v6": "fd02:97f2:b360:c5a6::/64"
}
```

Execute on the host:
`ping6 google.com`

You will see the ping working properly.

Execute the ipv6nat container:
`docker run -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock:ro -v /lib/modules:/lib/modules:ro --privileged --net=host robbertkl/ipv6nat`

Ping still works.

Now execute a container that make use of ipv6nat:
`docker container run -d --rm -it -p 80:80 navossoc/ipaddress`

Browse to: http://[your_ipv6]/

It works and you will see the ipv6nat working properly.

Note that ping stopped working as soon the container started using ipv6nat.

I tried a few other cenarios with docker-compose, custom networks, container or binary, etc. All have the same result.

Do you have any idea what that might be?
I'm missing something?

Besides that, all containers with ipv6 works properly.

PS: I need to reboot the host to get ipv6 working on the host again.
PS2: I did a quick test on Ubuntu 16.04/17.10 and it seems to work properly.

[]'s

**Comment by navossoc** [comment]
Sorry, I made more tests on different providers and I found the issue, it is not related to debian 9.

The problem is how Digital Ocean set up the network on Debian.
They are using virtual network interfaces.

**Original**
```bash
auto lo
iface lo inet loopback
        dns-nameservers  67.207.67.3 67.207.67.2

auto eth0
iface eth0 inet static
        hwaddress 46:60:01:xx:xx:xx
        address   159.89.xxx.xxx
        netmask   255.255.240.0
        gateway   159.89.xxx.xxx
        post-up ifup eth0:1
        post-up ifup eth0:2

auto eth0:1
iface eth0:1 inet6 static
        hwaddress 46:60:01:xx:xx:xx
        address   2604:A880:0800:xxxx:xxxx:xxxx:xxxx:xxxx/64
        gateway   2604:A880:0800:xxxx:xxxx:xxxx:xxxx:xxxx

auto eth0:2
iface eth0:2 inet static
        hwaddress 46:60:01:xx:xx:xx
        address   10.17.xxx.xxx/255.255.0.0
```

**Fix**
```bash
auto lo
iface lo inet loopback
        dns-nameservers  67.207.67.3 67.207.67.2

auto eth0
iface eth0 inet static
        hwaddress 46:60:01:xx:xx:xx
        address   159.89.xxx.xxx/20
        gateway   159.89.xxx.xxx

iface eth0 inet6 static
        hwaddress 46:60:01:xx:xx:xx
        address   2604:A880:0800:xxxx:xxxx:xxxx:xxxx:xxxx/64
        gateway   2604:A880:0800:xxxx:xxxx:xxxx:xxxx:xxxx

iface eth0 inet static
        hwaddress 46:60:01:xx:xx:xx
        address   10.17.xxx.xxx/16
```

Not sure if a fix is really needed, since is pretty simple to workaround this.

[]'s

**Comment by robbertkl** [comment]
Thanks for following up!
