### ISSUE TITLE
IPv6 gateway

### ISSUE THREAD

**Issue by j7an** [robbertkl/docker-ipv6nat#26]
I'm currently testing out ipv6nat. It seems to work well. I noticed the docker network command does not specify a gateway `docker network create --ipv6 --subnet=fd00:dead:beef::/48 mynetwork`. So only the IPv4 subnet has a gateway when I run `docker network inspect mynetwork`

Should a gateway be specified for IPv6? Would Nginx container see a visitor's real IPv6 address without a IPv6 gateway defined?

And how do I route host's IPv6 to Docker container's IPv6?

**Comment by robbertkl** [comment]
I'm using "Option A" myself, using startup flags for the Docker daemon: `--ipv6 --fixed-cidr-v6=fd00:dead:beef::/48`. This does automatically create a gateway:

```
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                },
                {
                    "Subnet": "fd00:dead:beef::/48",
                    "Gateway": "fd00:dead:beef::1"
                }
```

Not sure about user-defined networks, but would be very easy to try out. If we do need to set a gateway when creating the IPv6 user-defined network, I will change the instructions in the README, so please let me know if you happen to try this out.

**Comment by j7an** [comment]
Looks like an IPv6 gateway wasn't necessary for what I was trying to accomplish. Thanks for creating this project. I've been trying to get Nginx container work with IPv6 for several months. I created a pull request using your project at [IPv6 NAT](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/pull/98). You're welcome to look at the PR and let me know if improvements need to be made.
