### ISSUE TITLE
Not able to make it work

### ISSUE THREAD

**Issue by McBane87** [robbertkl/docker-ipv6nat#42]
Sorry for bothering, but I'm just not able to get this work.
I'm on CentOS7 with Docker 1.13.1.

My /etc/docker/daemon.json looks like this:
```
{
"ipv6": true,
"fixed-cidr-v6": "fd00:172:17:1::/64"
}
```
I've created the the ipv6nat like this:
```
docker create \
	--name ipv6nat \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-v /lib/modules:/lib/modules:ro \
	--net=host \
	--cap-add=NET_ADMIN \
	--cap-add=SYS_MODULE \
	--restart unless-stopped \
	robbertkl/ipv6nat
```

Is this enough? Should this now work out of the box?
I don't see any differences. What am I supposed to do to make the natting work?

If I create a container like this, nothing changes compared to without ipv6nat:
```
docker create \
	--name=somedocker\
	-p 1199:8888 \
	--restart unless-stopped \
	something/fromdocker
```

**Comment by robbertkl** [comment]
Please check the output of `ip6tables-save` (either on the host or within the ipv6nat container). If it works correctly it should show the created NAT rules here.

Also make sure you're not binding to a specific IPv4 address, just a port, but I see you've already edited your text to reflect this.

**Comment by bephinix** [comment]
Can you run the binary without docker and pass the `-debug` flag? This should print out all rules changes performed by docker-ipv6nat.

**Comment by McBane87** [comment]
> Please check the output of `ip6tables-save` (either on the host or within the ipv6nat container). If it works correctly it should show the created NAT rules here.
> 
> Also make sure you're not binding to a specific IPv4 address, just a port, but I see you've already edited your text to reflect this.

You are right, I see something if I remove the static ip-address from the `-p` option.
`-A DOCKER -p tcp -m tcp --dport 1199 -j DNAT --to-destination [fd00:172:17:1:0:242:ac11:8]:8888`

But in case I want the port to be bind to a special ipv6 address. How can I do that. Is that supported?
Things like `-p [ipv6:address]:123:456` aren't working because docker complains on run (not creation)

**Comment by robbertkl** [comment]
Unfortunately, this is not possible, as it would require built-in support from Docker.

You could use `com.docker.network.bridge.host_binding_ipv6` on a user-defined network (see README), but that might not be what you want.

**Comment by McBane87** [comment]
> Unfortunately, this is not possible, as it would require built-in support from Docker.
> 
> You could use `com.docker.network.bridge.host_binding_ipv6` on a user-defined network (see README), but that might not be what you want.

OK. Thank you anyway. I'll figure something out...
Anyways. Nice tools ;-)

**Comment by robbertkl** [comment]
Cool, good luck!

**Comment by bephinix** [comment]
> You are right, I see something if I remove the static ip-address from the `-p` option.
> `-A DOCKER -p tcp -m tcp --dport 1199 -j DNAT --to-destination [fd00:172:17:1:0:242:ac11:8]:8888`
> 
> But in case I want the port to be bind to a special ipv6 address. How can I do that. Is that supported?
> Things like `-p [ipv6:address]:123:456` aren't working because docker complains on run (not creation)

I am using Debian 9 and Debian 10 with the official Docker CE distribution and Docker-IPv6NAT. If I specify a static IPv6 address for a published port by `--publish`, a DNAT rule is created for IP6Tables.
