### ISSUE TITLE
DNAT unsupported revision

### ISSUE THREAD

**Issue by ADumaine** [robbertkl/docker-ipv6nat#47]
This is a new install of ubuntu 18.04 with the kernal updated to 5.3 and docker 19.03.06

The revision error appears to be due to the host system running iptables 1.6.1 and ipv6nat using 1.8.3.
as mentioned in https://github.com/moby/moby/issues/40428

`    0     0 DNAT       tcp      !bridge-tn30 *       ::/0                 2001:570:1a18:202::30  tcp dpt:19030 DNAT [unsupported revision]`

If this is the cause, how should it be fixed?  Can the version in ipv6nat be downgraded?  or do I need to upgrade ubuntu to 19.10?
Thanks!

**Comment by robbertkl** [comment]
Could you run `docker exec ipv6nat ls -l /sbin/iptables` for me and paste the output? Change "ipv6nat" to the name of your ipv6nat container.

**Comment by ADumaine** [comment]
Sorry, I went ahead and updated the OS to 20.04 which uses iptables 1.8.4 and the error is gone.

With 20.04 the command you requested results in the following:
`lrwxrwxrwx    1 root     root            20 Feb 28 19:05 /sbin/iptables -> xtables-legacy-multi`

I think it would be helpful to others if any other solutions were listed here.

**Comment by bephinix** [comment]
@robbertkl I think we can close this. :+1:

**Comment by robbertkl** [comment]
Agreed
