### ISSUE TITLE
Running multiple instances of docker-ipv6nat

### ISSUE THREAD

**Issue by Shuro** [robbertkl/docker-ipv6nat#68]
Hi there,
this is less of a bug and more of a generic (but unorthodox) question.

Is it safe to have multiple instances of ipv6nat running?
I have some preconfigured docker-compose files which I want to run on the same host, and there are at least two ipv6nat instances. Can they interfere with each other? 

Best regards,
Shuro

**Comment by robbertkl** [comment]
Hi @Shuro, I don't think that's a good idea and will probably cause issues.

The ipv6nat daemon manages ip6tables for the entire system, and communicates directly with the Docker daemon, not just for the containers within the same compose file, but for all IPv6 containers/networks. With multiple instances, this will conflict.

**Comment by Shuro** [comment]
I see, thank you very much. I'll check how I fix this problem on my end, running just one docker-ipv6nat container / binary.
