### ISSUE TITLE
ARMhf support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [robbertkl/docker-ipv6nat#7]
Can you please consider building a version that support ARMhf as well?

You can consider using https://hub.docker.com/r/forumi0721/alpine-armhf-base/, which could be used as a base to autobuild on Docker Hub as well.

A dedicated tag `armhf` would be nice to have too.

Thank you in advance!

**Comment by robbertkl** [comment]
As I'm unable to easily test this myself, perhaps you could give it a shot? I'm open to PRs.

Or perhaps you can manually verify that all it takes is a different (ARMhf) base image with a cross-compiled binary, I can make the necessary changes including ARMhf releases and automated builds.

**Comment by julianxhokaxhiu** [comment]
The only issue is that you should provide in your releases an ARMhf binary to work. I can provide a PR for the Dockerfile meanwhile :)

**Comment by robbertkl** [comment]
Just closed your PR since I'm playing with this myself for the moment. Since I wasn't aware of how cross arch images work on Docker hub / automated builds, I wasn't sure why I would need forumi0721's image, instead of something like `armhf/alpine`, but after reading https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/ I understand.

I've added an ARMhf binary release and set up automated build for master (`:latest-armhf`) and tags (`vX.X.X-armhf`). Can you check out `robbertkl/ipv6nat:latest-armhf`?

**Comment by julianxhokaxhiu** [comment]
Thank you! I'll try and I'll provide feedback asap :)

**Comment by julianxhokaxhiu** [comment]
Seems to work well! Tested on RPi2 :)

Thank you!

**Comment by robbertkl** [comment]
@julianxhokaxhiu Great, I'm creating a v0.2.0-armhf tag now. Thanks for the suggestion and your help.

I would, however, like to switch the base image to something else. I don't know where you've found `forumi0721/alpine-armhf-base`, but I'd like something where I can specify specific alpine versions, and preferably know what it's doing (source / Dockerfile). Can you tell me where it came from?

**Comment by julianxhokaxhiu** [comment]
Google honestly. I was looking for images that were recently updating regarding ARM support and that one came up. Unfortunately I didn't find sources either. I'm also a find of knowing what is actually doing, though preferrably through source code, but there is none.

Unfortunately enough this guys seems the only one who updates them frequently and offers an interesting stack to install/update/remove packages without playing with various package managers.

I'll keep you updated.

**Comment by julianxhokaxhiu** [comment]
FYI I found an open approach on building nearly from scratch, from an image that is more transparent, see https://hub.docker.com/r/armhf/alpine/

For an example, see https://github.com/cmosh/alpine-arm

**Comment by robbertkl** [comment]
Awesome, thanks for this. I took a slightly different approach, based on your info, see the`Dockerfile.armhf` for details. Basically I skipped the `cross-build-start`/`-end` stuff by wrapping each of the 2 commands I run.

I've also published a new release, making the ARMhf version official.
