### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by Knight1** [robbertkl/docker-ipv6nat#9]
Hey,

would you please also consider providing an automated builded aarch64 Image?

You could use this repo https://hub.docker.com/r/aarch64/alpine/
Or the builds from #7 https://hub.docker.com/r/forumi0721/alpine-aarch64-base/

Thanks!

**Comment by robbertkl** [comment]
Done! See https://hub.docker.com/r/robbertkl/ipv6nat/tags/

**Comment by Knight1** [comment]
Thank you so much! 🤗
